export const solar_system = [
  {
    id: 0,
    title: 'Sun',
    src: 'https://images-assets.nasa.gov/image/GSFC_20171208_Archive_e001435/GSFC_20171208_Archive_e001435~orig.jpg',
    texture: '/assets/sun.jpg',
    alt: 'sun',
    width: 200,
    height: 200,
  },
  {
    id: 1,
    title: 'Mercury',
    src: 'https://images-assets.nasa.gov/image/GSFC_20171208_Archive_e001544/GSFC_20171208_Archive_e001544~orig.png',
    texture: '/assets/mercury.jpg',
    alt: 'mercury',
    width: 200,
    height: 200,
  },
  {
    id: 2,
    title: 'Venus',
    src: 'https://images-assets.nasa.gov/image/PIA00271/PIA00271~orig.jpg',
    texture: '/assets/venus.jpg',
    alt: 'venus',
    width: 200,
    height: 200,
  },
  {
    id: 3,
    title: 'Earth',
    src: 'https://images-assets.nasa.gov/image/0202795/0202795~orig.jpg',
    texture: '/assets/earth.jpg',
    alt: 'earth',
    width: 200,
    height: 200,
  },
  {
    id: 4,
    title: 'Mars',
    src: 'https://images-assets.nasa.gov/image/PIA04591/PIA04591~orig.jpg',
    texture: '/assets/mars.jpg',
    alt: 'mars',
    width: 200,
    height: 200,
  },
  {
    id: 5,
    title: 'Jupiter',
    src: 'https://images-assets.nasa.gov/image/hubble-captures-vivid-auroras-in-jupiters-atmosphere_28000029525_o/hubble-captures-vivid-auroras-in-jupiters-atmosphere_28000029525_o~orig.jpg',
    texture: '/assets/jupiter.jpg',
    alt: 'jupiter',
    width: 200,
    height: 200,
  },
  {
    id: 6,
    title: 'Saturn',
    src: 'https://images-assets.nasa.gov/image/PIA02225/PIA02225~orig.jpg',
    texture: '/assets/saturn.jpg',
    alt: 'saturn',
    width: 200,
    height: 200,
  },
  {
    id: 7,
    title: 'Uranus',
    src: 'https://images-assets.nasa.gov/image/PIA18182/PIA18182~orig.jpg',
    texture: '/assets/uranus.jpg',
    alt: 'uranus',
    width: 200,
    height: 200,
  },
  {
    id: 8,
    title: 'Neptune',
    src: 'https://images-assets.nasa.gov/image/PIA01492/PIA01492~orig.jpg',
    texture: '/assets/neptune.jpg',
    alt: 'neptune',
    width: 200,
    height: 200,
  },
];
